const CONSTANTS = {
  ActionTypes: {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
    GET_NOTIFICATION: 'GET_NOTIFICATION',
    RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION',
    READ_NOTIFICATION: 'READ_NOTIFICATION',
    READ_NOTIFICATION_DONE: 'READ_NOTIFICATION_DONE',
    RESET_COUNTER: 'RESET_COUNTER',
    RESET_COUNTER_DONE: 'RESET_COUNTER_DONE',
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    UPDATE_NOTIFICATION_NEW_COUNTER: 'UPDATE_NOTIFICATION_NEW_COUNTER',
    NOTIFICATION_ARRIVED: 'NOTIFICATION_ARRIVED',
    UPDATE_NOTIFICATIONS: 'UPDATE_NOTIFICATIONS'
  }
};

export default CONSTANTS;
